rr_robot:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  top_wheel_le_joint_controller:
    type: effort_controllers/JointPositionController
    joint: top_wheel_le_joint
    pid: {p: 10000.0, i: 1000.0, d: 1000.0}

  top_wheel_te_joint_controller:
    type: effort_controllers/JointPositionController
    joint: top_wheel_te_joint
    pid: {p: 10000.0, i: 1000.0, d: 1000.0}